spring:
  application:
    name: Spring Demo for Okten
  profiles:
    active: store1
  datasource:
    url: "jdbc:postgresql://localhost:5432/XXX"
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.m7dnzbv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: products-db
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-sender}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    sun:
      rmi:
        transport:
          tcp: OFF